// ============================================================
// FILE: agent2-automation/automation_server.js
// WHAT: Agent 2 — handles everything AFTER a booking is made:
//
//   ALL appointments:
//   ✅ WhatsApp confirmation to patient (with Meet link if online)
//   ✅ WhatsApp notification to doctor (labelled ONLINE / OFFLINE)
//   ✅ WhatsApp reminder 1 day before
//
//   ONLINE only:
//   ✅ Send Google Meet link via WhatsApp 5 min before appointment
//      (link already exists — created by Agent 1 at booking time)
//   ✅ Send Paytm Business QR + invoice after consultation (35 min later)
//   ✅ Remind patient every 10 min if payment pending
//   ✅ Notify doctor when payment confirmed
//
//   OFFLINE only:
//   ✅ Patient visits clinic — payment handled in person
//   ✅ Doctor's calendar shows [OFFLINE] label clearly
//
// WHERE TO DEPLOY: Railway.app (separate project from Agent 1)
//   1. Push agent2-automation/ folder to a NEW GitHub repo
//   2. New Railway project → connect that repo
//   3. Add all env variables listed below
//   4. Copy Railway URL → set as AGENT2_WEBHOOK_URL in Agent 1's env vars
//
// NO ZOOM. NO EXTRA VIDEO API.
// Google Meet link is generated by Agent 1 via Google Calendar API
// and passed directly to this server in the /new-booking payload.
// ============================================================

const express  = require("express");
const cron     = require("node-cron");
const { google } = require("googleapis");
const twilio   = require("twilio");
const app      = express();
app.use(express.json());

// ── ENV VARIABLES — set on Railway, never hardcode ──────────
const TWILIO_ACCOUNT_SID    = process.env.TWILIO_ACCOUNT_SID;
const TWILIO_AUTH_TOKEN     = process.env.TWILIO_AUTH_TOKEN;
const TWILIO_WHATSAPP_FROM  = process.env.TWILIO_WHATSAPP_FROM; // "whatsapp:+14155238886"
const DOCTOR_WHATSAPP       = process.env.DOCTOR_WHATSAPP;      // "whatsapp:+91XXXXXXXXXX"
const PAYTM_QR_IMAGE_URL    = process.env.PAYTM_QR_IMAGE_URL;   // public URL of your Paytm QR image
const ONLINE_PRICE          = process.env.ONLINE_PRICE  || "500";
const DOCTOR_NAME           = process.env.DOCTOR_NAME   || "the doctor";
const GOOGLE_SERVICE_ACCOUNT_EMAIL = process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL;
const GOOGLE_PRIVATE_KEY           = process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, "\n");
const CALENDAR_ID                  = process.env.CALENDAR_ID;
// ────────────────────────────────────────────────────────────

// ── Twilio client ────────────────────────────────────────────
const twilioClient = twilio(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN);

async function sendWhatsApp(to, message, mediaUrl = null) {
  const toFormatted = to.startsWith("whatsapp:") ? to : `whatsapp:${to}`;
  try {
    const payload = { from: TWILIO_WHATSAPP_FROM, to: toFormatted, body: message };
    if (mediaUrl) payload.mediaUrl = [mediaUrl];
    const msg = await twilioClient.messages.create(payload);
    console.log(`📱 WhatsApp → ${to} | SID: ${msg.sid}`);
    return msg.sid;
  } catch (err) {
    console.error(`❌ WhatsApp failed to ${to}:`, err.message);
  }
}

// ── Google Calendar client (for daily scan cron) ─────────────
const calAuth = new google.auth.JWT(
  GOOGLE_SERVICE_ACCOUNT_EMAIL,
  null,
  GOOGLE_PRIVATE_KEY,
  ["https://www.googleapis.com/auth/calendar"]
);
const calendar = google.calendar({ version: "v3", auth: calAuth });

// ── In-memory stores ─────────────────────────────────────────
const pendingPayments = new Map(); // event_id → { patient_name, patient_whatsapp, attempts }
const scheduledTimers = new Map(); // key → timer reference

// ─────────────────────────────────────────────────────────────
// ROUTE 1: /new-booking
// Called by Agent 1 immediately after every calendar booking.
// Receives meet_link directly — no extra API call needed.
// ─────────────────────────────────────────────────────────────
app.post("/new-booking", async (req, res) => {
  const {
    event_id,
    patient_name,
    patient_whatsapp,
    date,
    time,
    type,
    meet_link,           // Google Meet link — already generated by Agent 1
    formatted_datetime,  // human-readable IST string
    is_reschedule,
  } = req.body;

  res.json({ received: true }); // respond immediately — don't block Vapi

  const action    = is_reschedule ? "rescheduled" : "confirmed";
  const typeLabel = type === "online" ? "Online Video Consultation (Google Meet)" : "In-Clinic Visit";
  const dateLabel = formatted_datetime || `${date} at ${time}`;

  console.log(`📅 New booking: ${patient_name} | ${type} | ${dateLabel} | Meet: ${meet_link || "N/A"}`);

  // ── 1. WhatsApp to PATIENT ────────────────────────────────
  let patientMsg =
    `Hello ${patient_name}! 🏥\n\n` +
    `Your appointment with *${DOCTOR_NAME}* has been *${action}*.\n\n` +
    `📋 *Type:* ${typeLabel}\n` +
    `📅 *When:* ${dateLabel}\n\n`;

  if (type === "online") {
    patientMsg +=
      `🎥 *Your Google Meet link:*\n${meet_link}\n\n` +
      `We'll also resend this link on WhatsApp *5 minutes before* your appointment starts.\n\n` +
      `💳 Payment of ₹${ONLINE_PRICE} is collected *after* your consultation.\n\n`;
  } else {
    patientMsg +=
      `📍 Please arrive *10 minutes early* at the clinic.\n` +
      `💳 Payment is collected at the clinic after consultation.\n\n`;
  }

  patientMsg += `_If you need to reschedule, please call us._\n_${DOCTOR_NAME}'s Clinic_`;
  await sendWhatsApp(patient_whatsapp, patientMsg);

  // ── 2. WhatsApp to DOCTOR ─────────────────────────────────
  let doctorMsg =
    `📅 *Appointment ${action.toUpperCase()}*\n\n` +
    `👤 *Patient:* ${patient_name}\n` +
    `📞 *WhatsApp:* ${patient_whatsapp}\n` +
    `🗓️ *When:* ${dateLabel}\n` +
    `💻 *Type:* ${type === "online" ? "🟢 ONLINE (Google Meet)" : "🏥 OFFLINE (In-Clinic)"}\n\n`;

  if (type === "online") {
    doctorMsg += `🎥 *Meet link:* ${meet_link}\n\n_Meet link will also be resent to patient 5 min before._`;
  } else {
    doctorMsg += `_Patient will visit the clinic. Collect payment in-person after consultation._`;
  }

  await sendWhatsApp(DOCTOR_WHATSAPP, doctorMsg);

  // ── 3. Schedule timed follow-up jobs ─────────────────────
  scheduleJobs(event_id, patient_name, patient_whatsapp, date, time, type, meet_link);
});

// ─────────────────────────────────────────────────────────────
// Schedule all timed jobs for an appointment
// ─────────────────────────────────────────────────────────────
function scheduleJobs(event_id, patient_name, patient_whatsapp, date, time, type, meet_link) {
  const appointmentTime = new Date(`${date}T${time}:00+05:30`);
  const now = new Date();

  // ── JOB A: 1-day reminder (ALL types) ────────────────────
  const oneDayBefore = new Date(appointmentTime.getTime() - 24 * 60 * 60 * 1000);
  if (oneDayBefore > now) {
    const delay = oneDayBefore.getTime() - now.getTime();
    const key = `reminder_${event_id}`;
    clearTimeout(scheduledTimers.get(key)); // cancel old if rescheduled
    scheduledTimers.set(key,
      setTimeout(async () => {
        const typeLabel = type === "online" ? "Online Video Consultation (Google Meet)" : "In-Clinic Visit";
        let msg =
          `⏰ *Appointment Reminder*\n\n` +
          `Hello ${patient_name}! Your *${typeLabel}* with *${DOCTOR_NAME}* is *tomorrow*.\n\n` +
          `📅 Time: ${time}\n\n`;

        if (type === "online") {
          msg += `🎥 Your Google Meet link:\n${meet_link}\n\n_We'll resend this link 5 minutes before your appointment._`;
        } else {
          msg += `📍 Please arrive 10 minutes early at the clinic.`;
        }

        await sendWhatsApp(patient_whatsapp, msg);
        scheduledTimers.delete(key);
      }, delay)
    );
    console.log(`⏳ 1-day reminder scheduled for ${patient_name}`);
  }

  // ── JOBS B & C: ONLINE only ───────────────────────────────
  if (type === "online") {

    // ── JOB B: 5 min before — resend Meet link ────────────
    // The Meet link is ALREADY created. We just resend it here.
    // No API call to Zoom or anything else needed.
    const fiveMinBefore = new Date(appointmentTime.getTime() - 5 * 60 * 1000);
    if (fiveMinBefore > now) {
      const delay = fiveMinBefore.getTime() - now.getTime();
      const key = `meet_remind_${event_id}`;
      clearTimeout(scheduledTimers.get(key));
      scheduledTimers.set(key,
        setTimeout(async () => {
          console.log(`🎥 Resending Google Meet link to ${patient_name}`);

          // Send to patient
          await sendWhatsApp(
            patient_whatsapp,
            `🎥 *Your appointment starts in 5 minutes!*\n\n` +
            `Hello ${patient_name}, here is your Google Meet link:\n\n` +
            `👉 ${meet_link}\n\n` +
            `Just tap the link to join your video consultation with *${DOCTOR_NAME}*.\n\n` +
            `_Works on mobile and desktop — no app download required._`
          );

          // Send to doctor
          await sendWhatsApp(
            DOCTOR_WHATSAPP,
            `🎥 *Appointment starting in 5 minutes*\n\n` +
            `Patient: ${patient_name} (${patient_whatsapp})\n\n` +
            `👉 ${meet_link}`
          );

          // Schedule payment QR 35 min later (after consultation ends)
          const paymentKey = `payment_qr_${event_id}`;
          scheduledTimers.set(paymentKey,
            setTimeout(() => sendPaymentQR(patient_name, patient_whatsapp, event_id), 35 * 60 * 1000)
          );

          scheduledTimers.delete(key);
        }, delay)
      );
      console.log(`⏳ Meet link resend scheduled for ${patient_name}`);
    }
  }
}

// ─────────────────────────────────────────────────────────────
// Send Paytm QR + invoice after consultation ends (online only)
// ─────────────────────────────────────────────────────────────
async function sendPaymentQR(patient_name, patient_whatsapp, event_id) {
  console.log(`💳 Sending Paytm QR to ${patient_name}`);

  await sendWhatsApp(
    patient_whatsapp,
    `✅ *Consultation Complete!*\n\n` +
    `Thank you ${patient_name} for consulting with *${DOCTOR_NAME}*.\n\n` +
    `*Invoice:*\n` +
    `📋 Online Consultation Fee: ₹${ONLINE_PRICE}\n\n` +
    `Please scan the *Paytm QR code* in the image below to complete your payment.\n\n` +
    `_Payment is secure. Nothing is stored by us._`,
    PAYTM_QR_IMAGE_URL // sends the Paytm QR as a WhatsApp image
  );

  // Start payment check loop
  pendingPayments.set(event_id, {
    patient_name,
    patient_whatsapp,
    attempts: 0,
    max_attempts: 6, // 6 × 10 min = 1 hour total
  });

  startPaymentCheckLoop(event_id);
}

// ─────────────────────────────────────────────────────────────
// Payment check loop — runs every 10 minutes
//
// HOW PAYTM PAYMENT IS CONFIRMED (simplest method):
// ─ Paytm Business instantly sends an SMS to the doctor's
//   registered mobile the moment any payment hits the QR.
//   So the doctor is notified automatically — zero setup.
//
// ─ This loop additionally sends WhatsApp reminders to the
//   patient if they haven't paid, and waits for the doctor
//   to call /confirm-payment (or for Paytm webhook to fire).
//
// ─ If Paytm enables webhooks on your account, point them to
//   /paytm-webhook and payment auto-confirms with no manual step.
// ─────────────────────────────────────────────────────────────
function startPaymentCheckLoop(event_id) {
  const intervalKey = `pay_interval_${event_id}`;

  const interval = setInterval(async () => {
    const record = pendingPayments.get(event_id);
    if (!record) { clearInterval(interval); scheduledTimers.delete(intervalKey); return; }

    record.attempts += 1;
    console.log(`⏳ Payment check ${record.attempts}/${record.max_attempts} for ${record.patient_name}`);

    if (record.attempts >= record.max_attempts) {
      // 1 hour passed — give up, alert doctor
      clearInterval(interval);
      scheduledTimers.delete(intervalKey);
      pendingPayments.delete(event_id);

      await sendWhatsApp(
        DOCTOR_WHATSAPP,
        `⚠️ *Payment not received after 1 hour*\n\n` +
        `Patient: ${record.patient_name}\n` +
        `WhatsApp: ${record.patient_whatsapp}\n\n` +
        `Please follow up manually.`
      );
      return;
    }

    // Send gentle reminder to patient
    await sendWhatsApp(
      record.patient_whatsapp,
      `💳 *Payment Reminder*\n\n` +
      `Hello ${record.patient_name}, your payment of ₹${ONLINE_PRICE} for today's consultation is still pending.\n\n` +
      `Please scan the Paytm QR sent earlier to complete payment. Thank you! 🙏`
    );
  }, 10 * 60 * 1000); // every 10 minutes

  scheduledTimers.set(intervalKey, interval);
}

// ─────────────────────────────────────────────────────────────
// ROUTE 2: Confirm payment (call this when doctor sees Paytm SMS)
//
// HOW TO USE:
// Doctor receives Paytm SMS → opens this URL in browser or bookmarks it.
// You can also build a simple button that calls this.
//
// curl -X POST https://your-agent2.railway.app/confirm-payment \
//   -H "Content-Type: application/json" \
//   -d '{"event_id":"CALENDAR_EVENT_ID","patient_name":"Patient Name"}'
// ─────────────────────────────────────────────────────────────
app.post("/confirm-payment", async (req, res) => {
  const { event_id, patient_name } = req.body;

  // Stop the payment check loop
  const intervalKey = `pay_interval_${event_id}`;
  const interval = scheduledTimers.get(intervalKey);
  if (interval) { clearInterval(interval); scheduledTimers.delete(intervalKey); }

  const record = pendingPayments.get(event_id);
  pendingPayments.delete(event_id);

  const name = patient_name || record?.patient_name || "the patient";
  console.log(`✅ Payment confirmed for ${name}`);

  // Notify doctor via WhatsApp
  await sendWhatsApp(
    DOCTOR_WHATSAPP,
    `✅ *Payment Confirmed!*\n\n` +
    `Payment of ₹${ONLINE_PRICE} received from *${name}*.\n\n` +
    `Consultation record complete. 🎉`
  );

  // Thank patient
  if (record?.patient_whatsapp) {
    await sendWhatsApp(
      record.patient_whatsapp,
      `✅ *Payment received!*\n\n` +
      `Thank you ${record.patient_name}! Your payment of ₹${ONLINE_PRICE} has been confirmed.\n\n` +
      `We hope you feel better soon! 🙏\n_${DOCTOR_NAME}'s Clinic_`
    );
  }

  res.json({ success: true });
});

// ─────────────────────────────────────────────────────────────
// ROUTE 3: Paytm Business webhook (if your account supports it)
// Set this URL in Paytm for Business app → Settings → Webhooks
// Paytm will POST here on successful payment → auto-confirms
// ─────────────────────────────────────────────────────────────
app.post("/paytm-webhook", async (req, res) => {
  console.log("Paytm webhook received:", JSON.stringify(req.body));
  const { status, custName, txnAmount } = req.body;

  if (status === "TXN_SUCCESS") {
    // Match by patient name to find the pending payment record
    for (const [event_id, record] of pendingPayments.entries()) {
      const nameMatch =
        record.patient_name.toLowerCase().includes((custName || "").toLowerCase()) ||
        (custName || "").toLowerCase().includes(record.patient_name.toLowerCase());

      if (nameMatch) {
        // Trigger confirmation
        await fetch(`http://localhost:${PORT}/confirm-payment`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ event_id, patient_name: record.patient_name }),
        });
        break;
      }
    }
  }
  res.json({ received: true });
});

// ─────────────────────────────────────────────────────────────
// CRON: Every day at 8 AM IST — scan calendar for upcoming
// appointments and re-register jobs (handles server restarts)
// ─────────────────────────────────────────────────────────────
cron.schedule("0 8 * * *", async () => {
  console.log("🔄 Daily calendar scan...");
  const today    = new Date();
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 2);

  try {
    const events = await calendar.events.list({
      calendarId: CALENDAR_ID,
      timeMin: today.toISOString(),
      timeMax: tomorrow.toISOString(),
      singleEvents: true,
      orderBy: "startTime",
    });

    for (const ev of events.data.items || []) {
      const props = ev.extendedProperties?.private || {};
      if (!props.patient_whatsapp) continue;

      const [datePart, timePart] = ev.start.dateTime?.split("T") || [];
      if (!datePart || !timePart) continue;

      scheduleJobs(
        ev.id,
        props.patient_name,
        props.patient_whatsapp,
        datePart,
        timePart.slice(0, 5),
        props.appointment_type,
        props.meet_link || "" // Google Meet link stored in event
      );
    }
    console.log(`✅ Scanned ${events.data.items?.length || 0} upcoming events`);
  } catch (err) {
    console.error("Daily scan error:", err.message);
  }
}, { timezone: "Asia/Kolkata" });

// Health check
app.get("/", (req, res) =>
  res.send(
    `Agent 2 — Automation Server running ✅\n` +
    `Pending payments: ${pendingPayments.size}\n` +
    `Scheduled timers: ${scheduledTimers.size}`
  )
);

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => console.log(`Agent 2 server on port ${PORT}`));
